backend:
  name: git-gateway
  branch: main

media_folder: "bilder/uploads"
public_folder: "/bilder/uploads"

collections:
  - name: "pages"
    label: "Seiteninhalte"
    files:
      - label: "Startseite"
        name: "home"
        file: "inhalt.json"
        fields:
          - {label: "Titel", name: "titel", widget: "string"}
          - {label: "Hero Überschrift", name: "heroHeadline", widget: "string"}
          - {label: "Hero Text", name: "heroSubline", widget: "string"}
          - {label: "Hero Bild", name: "heroBild", widget: "image"}
          - {label: "Biografie Text", name: "biografieText", widget: "text"}
          - {label: "Telefon", name: "kontakt", widget: "object", fields: [{label: "Nummer", name: "telefon", widget: "string"}, {label: "Email", name: "email", widget: "string"}]}
          - label: "Galerie"
            name: "galerieBilder"
            widget: "list"
            fields:
              - {label: "Titel", name: "titel", widget: "string"}
              - {label: "Beschreibung", name: "beschreibung", widget: "string"}
              - {label: "Bild", name: "bild", widget: "image"}
